spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    jpa:
      show-sql: false
      properties:
        hibernate:
          dialect: org.hibernate.dialect.H2Dialect
          format_sql: false
          use_sql_comments: true
      hibernate:
        ddl-auto: create-drop